apiVersion: v1
kind: Template
parameters:
  - name: IMAGE
    value: eclipse-mosquitto:1.4.12
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: broker-external
    spec:
      type: NodePort
      ports:
        - name: mqtt
          port: 1883
          targetPort: mqtt
      selector:
        app: maestro
        component: broker
  - apiVersion: v1
    kind: Service
    metadata:
      name: broker
    spec:
      type: ClusterIP
      ports:
        - name: mqtt
          port: 1883
          targetPort: mqtt
      selector:
        app: maestro
        component: broker
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: maestro-broker
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: broker
          app: maestro
      template:
        metadata:
          labels:
            component: broker
            app: maestro
        spec:
          containers:
            - name: broker
              image: ${IMAGE}
              ports:
                - name: mqtt
                  containerPort: 1883
              volumeMounts:
                - mountPath: /mosquitto/log
                  name: log
                - mountPath: /mosquitto/data
                  name: data
                - mountPath: /mosquitto/config
                  name: config
          volumes:
            - name: config
              configMap:
                name: broker-config
            - name: log
              emptyDir: {}
            - name: data
              emptyDir: {}
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: broker-config
    data:
      mosquitto.conf: |
        log_dest stdout
