apiVersion: v1
kind: Template
parameters:
  - name: IMAGE
    value: docker.io/maestroperf/maestro-broker:1.3.0
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: broker
    spec:
      type: ClusterIP
      ports:
        - name: mqtt
          port: 1883
          targetPort: mqtt
      selector:
        app: maestro
        component: broker
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: maestro-broker
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: broker
          app: maestro
      template:
        metadata:
          labels:
            component: broker
            app: maestro
        spec:
          containers:
            - name: broker
              image: ${IMAGE}
              ports:
                - name: mqtt
                  containerPort: 1883
              volumeMounts:
                - mountPath: /opt/maestro/broker/apache-activemq-5.15.3/data
                  name: data
          volumes:
            - name: data
              emptyDir: {}
