apiVersion: v1
kind: Template
parameters:
  - name: IMAGE
    value: docker.io/maestroperf/maestro-receiver:1.3.0
  - name: REPLICAS
    value: "1"
  - name: MAESTRO_BROKER
    required: true
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: maestro-receiver
    spec:
      replicas: ${{REPLICAS}}
      selector:
        matchLabels:
          component: receiver
          app: maestro
      template:
        metadata:
          labels:
            component: receiver
            app: maestro
        spec:
          containers:
            - name: receiver
              image: ${IMAGE}
              env:
                - name: MAESTRO_BROKER
                  value: ${MAESTRO_BROKER}
              volumeMounts:
                - mountPath: /maestro/receiver/logs
                  name: logging-volume
          volumes:
            - name: logging-volume
              emptyDir: {}
